USE codeup_test_db;
INSERT INTO albums (artist, name, sales)
VALUES ('Michael Jackson', 'Thriller', 43.3),
       ('AC/DC', 'Back in Black', 25.9),
       ('Pink Floyd', 'The Dark Side of the Moon', 22.7),
       ('Whitney Houston', 'The Bodyguard', 27.4),
       ('Meat Loaf', 'Bat Out of Hell', 20.6),
       ('Eagles', 'Their Greatest Hits (1971-1975', 32.2),
       ('Bee Gees', 'Saturday Night Fever', 19),
       ('Fleetwood Mac', 'Rumors', 27.9),
       ('Shania Twain', 'Come on Over', 29.6),
       ('Led Zeppelin', 'Led Zeppelin IV', 29.0),
       ('Spice Girls', 'Spice', 28),
       ('Alanis Morissette', 'Jagged Little Pill', 24.8),
       ('Celine Dion', 'Falling into You', 20.2),
       ('The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', 13.1),
       ('Eagles', 'Hotel California', 21.5),
       ('Mariah Carey', 'Music Box', 19.5),
       ('Various Artists', 'Dirty Dancing', 17.9),
       ('Celine Dion', 'Let''s Talk About Love', 19.3),
       ('The Beatles', '1', 21.6),
       ('Adele', '21', 21.3),
       ('The Beatles', 'Abbey Road', 14.4),
       ('Bruce Springsteen', 'Born in the U.S.A.', 19.6),
       ('Dire Straights', 'Brothers in Arms', 18.6),
       ('Whitney Houston', 'Whitney Houston', 17.2),
       ('James Horner', 'Titanic: Music from the Motion Picture', 18.1),
       ('Madonna', 'The Immaculate Collection', 19.4),
       ('Metallica', 'Metallica', 19.9),
       ('Michael Jackson', 'Bad', 18.4),
       ('Michael Jackson', 'Dangerous', 16.3),
       ('Nirvana', 'Nevermind', 16.7),
       ('Pink Floyd', 'The Wall', 17.6),
       ('Santana', 'Supernatural', 20.5),
       ('Guns N'' Roses', 'Appetite for Destruction', 21.3);